# Generated by Django 4.1.7 on 2024-02-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0003_comment_created_on_post_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='featured_image/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
