# Generated by Django 4.1.7 on 2024-03-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0007_rename_content_post_body_remove_post_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
